name: Informe semanal de cartera

on:

  # Permite ejecutar el bot manualmente desde GitHub
  workflow_dispatch:

  # Ejecutar una vez por semana
  # Domingo a las 17:00 UTC
  # = 19:00 en España durante horario de verano
  schedule:
    - cron: "0 17 * * 0"


jobs:

  ejecutar-bot:

    runs-on: ubuntu-latest

    steps:

      # ----------------------------------------------------
      # Descargar código
      # ----------------------------------------------------

      - name: Descargar código
        uses: actions/checkout@v4


      # ----------------------------------------------------
      # Configurar Python
      # ----------------------------------------------------

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      # ----------------------------------------------------
      # Instalar dependencias
      # ----------------------------------------------------

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      # ----------------------------------------------------
      # Ejecutar bot
      # ----------------------------------------------------

      - name: Ejecutar bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

        run: |
          python bot_cartera_telegram.py

      # ----------------------------------------------------
      # Instalar dependencias
      # ----------------------------------------------------

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install yfinance requests


      # ----------------------------------------------------
      # Ejecutar bot
      # ----------------------------------------------------

      - name: Ejecutar bot

        env:

          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

          CHAT_ID: ${{ secrets.CHAT_ID }}

        run: |

          python bot_cartera_telegram.py
